/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fanchen_update_jni_PatchUpdate */

#ifndef _Included_com_fanchen_update_jni_PatchUpdate
#define _Included_com_fanchen_update_jni_PatchUpdate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fanchen_update_jni_PatchUpdate
 * Method:    update
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fanchen_update_jni_PatchUpdate_update
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
